name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --base-href="/expense-tracker/"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/expense-tracker --no-silent
